### ISSUE TITLE
Blank Scope Context information inside on_actions (HOI4)

### ISSUE THREAD

**Issue by insilications** [cwtools/cwtools-vscode#92] opened 2023-07-21 11:27 UTC
Everything else is working perfectly. It seems that https://github.com/cwtools/cwtools-hoi4-config/blob/master/Config/on_actions.cwt is wrong. I've managed to fix it by changing some aspects of it. I've read the wiki for CWTools (.cwt config file format guidance and architecture). I'm a C/C++ programmer primarily and I like FP, but I'm having a hard time understanding the F# that parses and generates the config rules used by the language server. So I have no idea what is really going on behind my "fix".

As an example of my changes, my modified on_actions.cwt:

Config/on_actions.cwt:
```
types = {
	type[on_actions] = {
		path = "game/common/on_actions"
		## type_key_filter = on_nuke_drop
		subtype[on_nuke_drop] = {}
		## type_key_filter = on_new_term_election
		subtype[on_new_term_election] = {}
	}
}

on_actions = {
	## replace_scope = { THIS = country ROOT = country FROM = state }
	## cardinality = 0..1
	on_nuke_drop = {
		## cardinality = 0..1
		random_events = {
			## cardinality = 0..inf
			int = 0
			## cardinality = 0..inf
			int = <event>
		}
		## cardinality = 0..1
		effect = {
			alias_name[effect] = alias_match_left[effect]
		}
	}

	## replace_scope = { THIS = country ROOT = country FROM = country }
	## cardinality = 0..1
	on_new_term_election = {
		## cardinality = 0..1
		random_events = {
			## cardinality = 0..inf
			int = 0
			## cardinality = 0..inf
			int = <event>
		}
		## cardinality = 0..1
		effect = {
			alias_name[effect] = alias_match_left[effect]
		}
	}
}
```

The on_actions used inside my mod:

```
on_actions = {
	on_nuke_drop = {
		effect = {
			FROM = {
				save_event_target_as = the_nuke
				log = "[GetDateText]: Nuke dropped on [This.GetName], controller [This.controller.GetName], dropped by [Root.GetName]"
			}
		}
	}
	on_new_term_election = {
		effect = {
			FROM = {
			}
		}
	}
}
```

It is even registering the save_event_target_as = the_nuke in the model for proper usage in localisation. In the latest upstream `cwtools-hoi4-config`, that also was not working properly. 
![2023-07-19_02-14](https://github.com/cwtools/cwtools-vscode/assets/55766834/df0fad56-89c8-4a13-8444-cce3a845f853)

In the attached screenshots you can see the the Scope Context information inside on_actions being successfully provided inside both `on_nuke_drop`  and `on_new_term_election`. 
![2023-07-19_01-59](https://github.com/cwtools/cwtools-vscode/assets/55766834/31a65c95-99ca-4b42-aca3-a9e2b583b638)
![2023-07-19_01-59_1](https://github.com/cwtools/cwtools-vscode/assets/55766834/68ecce4d-1a32-468e-b246-4ceacee4beaf)

I have no idea what is really going on behind my "fix".

**Comment by EndsM** [comment] 2023-11-19 09:32
Yes, I have the same problem, the language suggestion inside on_action/effect is missing. Without language suggestion is quite painful while work inside the on actions.

**Comment by Pelmen323** [comment] 2024-06-24 20:27
I can't reproduce the issue, it should've been fixed in https://github.com/cwtools/cwtools-hoi4-config/commit/98113cb1bf43812d5753f9ea937b31d3a483ce3a

Please report hoi4 issues here https://github.com/cwtools/cwtools-hoi4-config/issues

**Comment by insilications** [comment] 2024-06-24 20:36
Yes, it seems it should've been fixed. I can't test it right now.

**Closed** 2024-08-26 09:03 UTC
